const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const JournalEntry = sequelize.define('JournalEntry', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },
  tenantId: {
    type: DataTypes.UUID,
    allowNull: false,
  },
  entryNumber: {
    type: DataTypes.STRING(50),
    allowNull: false,
    validate: {
      notEmpty: { msg: 'Entry number is required' },
      len: { args: [2, 50], msg: 'Entry number must be between 2 and 50 characters' },
    },
  },
  entryDate: {
    type: DataTypes.DATEONLY,
    allowNull: false,
    validate: {
      isDate: { msg: 'Valid entry date is required' },
    },
  },
  reference: {
    type: DataTypes.STRING(100),
    allowNull: true,
  },
  description: {
    type: DataTypes.TEXT,
    allowNull: true,
  },
  fiscalPeriodId: {
    type: DataTypes.UUID,
    allowNull: true,
  },
  status: {
    type: DataTypes.ENUM('draft', 'posted'),
    defaultValue: 'draft',
    validate: {
      isIn: {
        args: [['draft', 'posted']],
        msg: 'Status must be draft or posted',
      },
    },
  },
  postedAt: {
    type: DataTypes.DATE,
    allowNull: true,
  },
  postedBy: {
    type: DataTypes.UUID,
    allowNull: true,
  },
  isAutoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
  },
  source: {
    type: DataTypes.STRING(50),
    allowNull: true,
  },
  sourceId: {
    type: DataTypes.UUID,
    allowNull: true,
  },
  createdBy: {
    type: DataTypes.UUID,
    allowNull: true,
  },
  updatedBy: {
    type: DataTypes.UUID,
    allowNull: true,
  },
}, {
  tableName: 'journal_entries',
  underscored: true,
  timestamps: true,
  paranoid: false,
  indexes: [
    {
      unique: true,
      fields: ['entry_number', 'tenant_id'],
      name: 'unique_je_tenant',
    },
    {
      fields: ['entry_date'],
      name: 'idx_je_date',
    },
    {
      fields: ['tenant_id'],
      name: 'idx_je_tenant',
    },
    {
      fields: ['status'],
      name: 'idx_je_status',
    },
  ],
  defaultScope: {
    where: {},
    order: [['entry_date', 'DESC']],
  },
  scopes: {
    draft: {
      where: { status: 'draft' },
    },
    posted: {
      where: { status: 'posted' },
    },
    byTenant: (tenantId) => ({
      where: { tenantId },
    }),
  },
});

module.exports = JournalEntry;