const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/AssetInsuranceController');
const { authMiddleware } = require('../middleware/authMiddleware');
const { requirePermission } = require('../middleware/rbacMiddleware');
const { createValidation, updateValidation, idValidation } = require('../validators/assetInsuranceValidation');
router.use(authMiddleware);
router.get('/next-number', requirePermission('fixedasset.insurance'), (req, res, next) => ctrl.getNextNumber(req, res, next));
router.get('/expiring', requirePermission('fixedasset.view'), (req, res, next) => ctrl.getExpiring(req, res, next));
router.get('/', requirePermission('fixedasset.view'), (req, res, next) => ctrl.getAll(req, res, next));
router.get('/:id', requirePermission('fixedasset.view'), idValidation, (req, res, next) => ctrl.getById(req, res, next));
router.post('/', requirePermission('fixedasset.insurance'), createValidation, (req, res, next) => ctrl.create(req, res, next));
router.put('/:id', requirePermission('fixedasset.insurance'), idValidation, updateValidation, (req, res, next) => ctrl.update(req, res, next));
router.delete('/:id', requirePermission('fixedasset.delete'), idValidation, (req, res, next) => ctrl.delete(req, res, next));
module.exports = router;
