class JournalEntryDTO {
  static toResponse(entry) {
    if (!entry) return null;
    const data = entry.toJSON ? entry.toJSON() : entry;

    // Handle associated lines
    let lines = [];
    if (data.lines && Array.isArray(data.lines)) {
      lines = data.lines.map(line => JournalEntryLineDTO.toResponse(line));
    }

    // Calculate totals
    const totalDebit = lines.reduce((sum, l) => sum + Number(l.debit || 0), 0);
    const totalCredit = lines.reduce((sum, l) => sum + Number(l.credit || 0), 0);

    return {
      id: data.id,
      tenantId: data.tenantId,
      entryNumber: data.entryNumber,
      entryDate: data.entryDate,
      reference: data.reference || null,
      description: data.description || null,
      fiscalPeriodId: data.fiscalPeriodId || null,
      status: data.status,
      postedAt: data.postedAt || null,
      postedBy: data.postedBy || null,
      isAutoGenerated: data.isAutoGenerated || false,
      source: data.source || null,
      sourceId: data.sourceId || null,
      createdBy: data.createdBy || null,
      updatedBy: data.updatedBy || null,
      createdAt: data.createdAt,
      updatedAt: data.updatedAt,
      lines,
      totalDebit,
      totalCredit,
    };
  }

  static toListResponse(entries) {
    if (!entries) return [];
    return entries.map(entry => JournalEntryDTO.toResponse(entry));
  }
}

class JournalEntryLineDTO {
  static toResponse(line) {
    if (!line) return null;
    const data = line.toJSON ? line.toJSON() : line;

    return {
      id: data.id,
      tenantId: data.tenantId,
      journalEntryId: data.journalEntryId,
      accountId: data.accountId,
      lineNumber: data.lineNumber,
      description: data.description || null,
      debit: Number(data.debit || 0),
      credit: Number(data.credit || 0),
      createdAt: data.createdAt,
      updatedAt: data.updatedAt,
      // Include account if eager loaded
      account: data.account ? {
        id: data.account.id,
        code: data.account.code,
        name: data.account.name,
        type: data.account.type,
      } : null,
    };
  }

  static toListResponse(lines) {
    if (!lines) return [];
    return lines.map(line => JournalEntryLineDTO.toResponse(line));
  }
}

module.exports = { JournalEntryDTO, JournalEntryLineDTO };