/**
 * EzeeFlo Employee App - Test Cases
 * 
 * Comprehensive test cases for the mobile application.
 * All test cases validate integration with the existing HR & Payroll backend.
 */

export const TEST_CASES = {
  // 1. Authentication Tests
  AUTH: {
    TC_AUTH_001: {
      id: 'TC-AUTH-001',
      name: 'Login with valid username and password',
      module: 'Login',
      priority: 'P0',
      steps: [
        'Launch app',
        'Enter valid username',
        'Enter valid password',
        'Tap Sign In',
      ],
      expected: 'User is authenticated and redirected to company selection or dashboard',
      apiEndpoint: 'POST /api/hr/auth/login',
    },
    TC_AUTH_002: {
      id: 'TC-AUTH-002',
      name: 'Login with valid email and password',
      module: 'Login',
      priority: 'P0',
      steps: ['Launch app', 'Enter valid email', 'Enter valid password', 'Tap Sign In'],
      expected: 'User is authenticated successfully',
    },
    TC_AUTH_003: {
      id: 'TC-AUTH-003',
      name: 'Login with employee number',
      module: 'Login',
      priority: 'P1',
      steps: ['Launch app', 'Enter employee number', 'Enter valid password', 'Tap Sign In'],
      expected: 'User is authenticated successfully',
    },
    TC_AUTH_004: {
      id: 'TC-AUTH-004',
      name: 'Login with invalid credentials',
      module: 'Login',
      priority: 'P0',
      steps: ['Enter invalid username', 'Enter invalid password', 'Tap Sign In'],
      expected: 'Error message displayed: "Invalid credentials"',
    },
    TC_AUTH_005: {
      id: 'TC-AUTH-005',
      name: 'Login with empty fields',
      module: 'Login',
      priority: 'P1',
      steps: ['Leave username empty', 'Tap Sign In'],
      expected: 'Validation error: "Please enter your username..."',
    },
    TC_AUTH_006: {
      id: 'TC-AUTH-006',
      name: 'Biometric login - Fingerprint/Face ID',
      module: 'Login',
      priority: 'P1',
      steps: ['Enable biometric login in settings', 'Logout', 'Tap biometric login button', 'Authenticate with biometric'],
      expected: 'User is authenticated without entering password',
    },
    TC_AUTH_007: {
      id: 'TC-AUTH-007',
      name: 'Remember Me functionality',
      module: 'Login',
      priority: 'P2',
      steps: ['Check "Remember Me"', 'Login successfully', 'Kill app', 'Reopen app'],
      expected: 'Session is restored without re-entering credentials',
    },
    TC_AUTH_008: {
      id: 'TC-AUTH-008',
      name: 'Session timeout',
      module: 'Login',
      priority: 'P1',
      steps: ['Login successfully', 'Leave app idle for 30+ minutes', 'Return to app'],
      expected: 'User is logged out and redirected to login screen',
    },
    TC_AUTH_009: {
      id: 'TC-AUTH-009',
      name: 'JWT token refresh',
      module: 'Login',
      priority: 'P1',
      steps: ['Login successfully', 'Wait for token near expiry', 'Perform an API request'],
      expected: 'Token is refreshed automatically without requiring re-login',
    },
    TC_AUTH_010: {
      id: 'TC-AUTH-010',
      name: 'Multi-company selection',
      module: 'Login',
      priority: 'P1',
      steps: ['Login with user having multiple companies', 'Select a company from the list'],
      expected: 'User is redirected to dashboard with selected company context',
    },
    TC_AUTH_011: {
      id: 'TC-AUTH-011',
      name: 'Logout clears all local data',
      module: 'Login',
      priority: 'P1',
      steps: ['Login successfully', 'Navigate to Settings', 'Tap Sign Out'],
      expected: 'All tokens, user data, and company data are cleared from secure storage',
    },
  },

  // 2. Dashboard Tests
  DASHBOARD: {
    TC_DASH_001: {
      id: 'TC-DASH-001',
      name: 'Dashboard loads with employee data',
      module: 'Dashboard',
      priority: 'P0',
      steps: ['Login and select company', 'Dashboard screen loads'],
      expected: 'Employee name, number, profile picture, company, department, designation displayed',
      apiEndpoint: 'GET /api/hr/dashboard/summary',
    },
    TC_DASH_002: {
      id: 'TC-DASH-002',
      name: 'Today attendance status displayed',
      module: 'Dashboard',
      priority: 'P0',
      steps: ['View dashboard'],
      expected: 'Check-in/out status with times displayed',
    },
    TC_DASH_003: {
      id: 'TC-DASH-003',
      name: 'Leave balances displayed',
      module: 'Dashboard',
      priority: 'P1',
      steps: ['View dashboard'],
      expected: 'Leave balance cards with remaining days shown',
    },
    TC_DASH_004: {
      id: 'TC-DASH-004',
      name: 'Upcoming holidays displayed',
      module: 'Dashboard',
      priority: 'P2',
      steps: ['View dashboard', 'Scroll to holidays section'],
      expected: 'Upcoming holidays with dates shown',
    },
    TC_DASH_005: {
      id: 'TC-DASH-005',
      name: 'Quick actions navigate correctly',
      module: 'Dashboard',
      priority: 'P1',
      steps: ['Tap each quick action: Check In, Apply Leave, Payslips, Directory'],
      expected: 'Each action navigates to the correct screen',
    },
    TC_DASH_006: {
      id: 'TC-DASH-006',
      name: 'Pull-to-refresh updates data',
      module: 'Dashboard',
      priority: 'P2',
      steps: ['Pull down on dashboard to refresh'],
      expected: 'Loading indicator shown, data refreshed from API',
    },
  },

  // 3. Attendance Tests
  ATTENDANCE: {
    TC_ATT_001: {
      id: 'TC-ATT-001',
      name: 'Check-In with GPS location',
      module: 'Attendance',
      priority: 'P0',
      steps: ['Navigate to Attendance', 'Tap Check In', 'Grant location permission if prompted'],
      expected: 'Check-in recorded with GPS coordinates; success message displayed',
      apiEndpoint: 'POST /api/hr/attendance/mark',
    },
    TC_ATT_002: {
      id: 'TC-ATT-002',
      name: 'Check-Out with GPS location',
      module: 'Attendance',
      priority: 'P0',
      steps: ['Navigate to Attendance', 'Tap Check Out'],
      expected: 'Check-out recorded; total hours calculated',
    },
    TC_ATT_003: {
      id: 'TC-ATT-003',
      name: 'Break Start and End',
      module: 'Attendance',
      priority: 'P1',
      steps: ['Check in first', 'Tap Take Break', 'Tap End Break'],
      expected: 'Break times recorded correctly',
    },
    TC_ATT_004: {
      id: 'TC-ATT-004',
      name: 'GPS validation - outside geofence',
      module: 'Attendance',
      priority: 'P1',
      steps: ['Attempt check-in from outside office area', 'Confirm warning dialog'],
      expected: 'Warning displayed about being outside office area; check-in proceeds after confirmation',
    },
    TC_ATT_005: {
      id: 'TC-ATT-005',
      name: 'Location permission denied',
      module: 'Attendance',
      priority: 'P2',
      steps: ['Deny location permission', 'Attempt check-in'],
      expected: 'Alert explaining location is needed for attendance',
    },
    TC_ATT_006: {
      id: 'TC-ATT-006',
      name: 'Offline attendance sync',
      module: 'Attendance',
      priority: 'P1',
      steps: ['Go offline (airplane mode)', 'Check in', 'Go back online'],
      expected: 'Offline record saved locally; auto-synced when online; success message shown',
    },
    TC_ATT_007: {
      id: 'TC-ATT-007',
      name: 'Attendance history displayed',
      module: 'Attendance',
      priority: 'P1',
      steps: ['Navigate to Attendance History'],
      expected: 'List of attendance records with dates, times, and status shown',
    },
    TC_ATT_008: {
      id: 'TC-ATT-008',
      name: 'Attendance calendar view',
      module: 'Attendance',
      priority: 'P2',
      steps: ['Navigate to Attendance Calendar'],
      expected: 'Monthly calendar with attendance days highlighted',
    },
  },

  // 4. Leave Tests
  LEAVE: {
    TC_LEAVE_001: {
      id: 'TC-LEAVE-001',
      name: 'View leave balances',
      module: 'Leave',
      priority: 'P0',
      steps: ['Navigate to Leave tab'],
      expected: 'All leave balances displayed with remaining/used/total',
      apiEndpoint: 'GET /api/hr/leave-balances',
    },
    TC_LEAVE_002: {
      id: 'TC-LEAVE-002',
      name: 'Apply for leave',
      module: 'Leave',
      priority: 'P0',
      steps: ['Tap Apply', 'Select leave type', 'Enter dates', 'Enter reason', 'Submit'],
      expected: 'Leave application submitted; pending approval shown',
      apiEndpoint: 'POST /api/hr/leave-applications',
    },
    TC_LEAVE_003: {
      id: 'TC-LEAVE-003',
      name: 'Apply leave with insufficient balance',
      module: 'Leave',
      priority: 'P1',
      steps: ['Select leave type with low balance', 'Enter dates exceeding balance'],
      expected: 'Error or warning about insufficient balance',
    },
    TC_LEAVE_004: {
      id: 'TC-LEAVE-004',
      name: 'Cancel leave application',
      module: 'Leave',
      priority: 'P2',
      steps: ['View pending leave application', 'Tap Cancel'],
      expected: 'Leave status changed to cancelled',
    },
    TC_LEAVE_005: {
      id: 'TC-LEAVE-005',
      name: 'Leave calendar view',
      module: 'Leave',
      priority: 'P2',
      steps: ['Navigate to Leave Calendar'],
      expected: 'Calendar showing leave days, holidays, and weekends',
    },
  },

  // 5. Payroll Tests
  PAYROLL: {
    TC_PAY_001: {
      id: 'TC-PAY-001',
      name: 'View payslips list',
      module: 'Payroll',
      priority: 'P0',
      steps: ['Navigate to Payroll tab'],
      expected: 'Recent payslips displayed with amounts and dates',
      apiEndpoint: 'GET /api/hr/payslips',
    },
    TC_PAY_002: {
      id: 'TC-PAY-002',
      name: 'View salary breakdown',
      module: 'Payroll',
      priority: 'P0',
      steps: ['View payroll screen'],
      expected: 'Net salary, basic, allowances, deductions displayed',
    },
    TC_PAY_003: {
      id: 'TC-PAY-003',
      name: 'Download payslip as PDF',
      module: 'Payroll',
      priority: 'P1',
      steps: ['Tap on a payslip', 'Tap Download'],
      expected: 'PDF downloaded to device',
    },
    TC_PAY_004: {
      id: 'TC-PAY-004',
      name: 'Payroll history by year',
      module: 'Payroll',
      priority: 'P2',
      steps: ['Navigate to Payroll History'],
      expected: 'Yearly payroll summary shown',
    },
  },

  // 6. Documents Tests
  DOCUMENTS: {
    TC_DOC_001: {
      id: 'TC-DOC-001',
      name: 'View employee documents',
      module: 'Documents',
      priority: 'P0',
      steps: ['Navigate to More > Documents'],
      expected: 'List of employee documents with types and expiry status',
    },
    TC_DOC_002: {
      id: 'TC-DOC-002',
      name: 'Document expiry alerts',
      module: 'Documents',
      priority: 'P1',
      steps: ['View documents with expiring dates'],
      expected: 'Documents marked as "Expiring Soon" or "Expired"',
    },
    TC_DOC_003: {
      id: 'TC-DOC-003',
      name: 'Download document',
      module: 'Documents',
      priority: 'P1',
      steps: ['Tap Download on a document'],
      expected: 'File downloaded to device',
    },
  },

  // 7. Notifications Tests
  NOTIFICATIONS: {
    TC_NOTIF_001: {
      id: 'TC-NOTIF-001',
      name: 'View notifications list',
      module: 'Notifications',
      priority: 'P1',
      steps: ['Navigate to More > Notifications'],
      expected: 'List of notifications with read/unread status',
    },
    TC_NOTIF_002: {
      id: 'TC-NOTIF-002',
      name: 'Mark notification as read',
      module: 'Notifications',
      priority: 'P2',
      steps: ['Tap on an unread notification'],
      expected: 'Notification marked as read',
    },
    TC_NOTIF_003: {
      id: 'TC-NOTIF-003',
      name: 'Unread badge count',
      module: 'Notifications',
      priority: 'P2',
      steps: ['View More screen'],
      expected: 'Unread count badge shown on Notifications menu item',
    },
  },

  // 8. Security Tests
  SECURITY: {
    TC_SEC_001: {
      id: 'TC-SEC-001',
      name: 'JWT token stored in secure storage',
      module: 'Security',
      priority: 'P0',
      steps: ['Login', 'Check secure storage'],
      expected: 'Token stored in expo-secure-store (encrypted)',
    },
    TC_SEC_002: {
      id: 'TC-SEC-002',
      name: 'API calls include JWT in Authorization header',
      module: 'Security',
      priority: 'P0',
      steps: ['Make any authenticated API call', 'Inspect request headers'],
      expected: 'Authorization: Bearer <token> header present',
    },
    TC_SEC_003: {
      id: 'TC-SEC-003',
      name: 'API calls include X-Company-Id header',
      module: 'Security',
      priority: 'P0',
      steps: ['Make any company-scoped API call', 'Inspect request headers'],
      expected: 'X-Company-Id header present with active company ID',
    },
    TC_SEC_004: {
      id: 'TC-SEC-004',
      name: 'Expired token triggers re-login',
      module: 'Security',
      priority: 'P0',
      steps: ['Wait for token to expire', 'Make an API call'],
      expected: 'Auto-refresh attempted; if fails, user redirected to login',
    },
    TC_SEC_005: {
      id: 'TC-SEC-005',
      name: 'RBAC enforcement - unauthorized endpoint',
      module: 'Security',
      priority: 'P1',
      steps: ['Login as employee (non-manager)', 'Attempt to access manager-only endpoint'],
      expected: '403 Forbidden or access denied',
    },
  },

  // 9. Offline Tests
  OFFLINE: {
    TC_OFF_001: {
      id: 'TC-OFF-001',
      name: 'Offline check-in saved locally',
      module: 'Offline',
      priority: 'P1',
      steps: ['Enable airplane mode', 'Perform check-in'],
      expected: 'Attendance saved to local storage with "offline" flag',
    },
    TC_OFF_002: {
      id: 'TC-OFF-002',
      name: 'Auto-sync when back online',
      module: 'Offline',
      priority: 'P1',
      steps: ['Disable airplane mode after offline check-in', 'Wait for sync interval'],
      expected: 'Offline records synced to server automatically',
    },
    TC_OFF_003: {
      id: 'TC-OFF-003',
      name: 'Sync conflict resolution',
      module: 'Offline',
      priority: 'P2',
      steps: ['Create offline record', 'Create conflicting server record', 'Sync'],
      expected: 'Conflict handled gracefully (latest timestamp wins)',
    },
  },

  // 10. Performance Tests
  PERFORMANCE: {
    TC_PERF_001: {
      id: 'TC-PERF-001',
      name: 'App launch time under 3 seconds',
      module: 'Performance',
      priority: 'P1',
      steps: ['Cold start the app'],
      expected: 'Splash screen shown, app ready in < 3 seconds',
    },
    TC_PERF_002: {
      id: 'TC-PERF-002',
      name: 'Dashboard load time under 2 seconds',
      module: 'Performance',
      priority: 'P2',
      steps: ['Login', 'Wait for dashboard to render'],
      expected: 'All dashboard widgets loaded within 2 seconds',
    },
    TC_PERF_003: {
      id: 'TC-PERF-003',
      name: 'Smooth list scrolling with 100+ items',
      module: 'Performance',
      priority: 'P2',
      steps: ['Navigate to directory with 100+ employees', 'Scroll rapidly'],
      expected: 'No jank or frame drops; FlatList virtualization works',
    },
  },
};

export default TEST_CASES;
