-- EzeeFlo HR & Payroll -- Complete Schema (74 tables)
-- MariaDB 10.11 Compatible

CREATE DATABASE IF NOT EXISTS ezeeflo_hr_payroll CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ezeeflo_hr_payroll;

CREATE TABLE `allowance_types` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(150) NOT NULL,
  `allowance_category` enum('Fixed','Variable','Recurring','OneTime') DEFAULT 'Fixed',
  `is_taxable` tinyint(1) DEFAULT '1',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `allowance_types_tenant_id_code` (`tenant_id`,`code`),
  KEY `allowance_types_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `attendances` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `shift_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `attendance_date` date NOT NULL,
  `check_in_time` datetime DEFAULT NULL,
  `check_out_time` datetime DEFAULT NULL,
  `check_in_method` enum('Manual','Biometric','GPS','Mobile','Face','Web') DEFAULT 'Manual',
  `check_out_method` enum('Manual','Biometric','GPS','Mobile','Face','Web') DEFAULT 'Manual',
  `check_in_location` varchar(255) DEFAULT NULL,
  `check_out_location` varchar(255) DEFAULT NULL,
  `status` enum('Present','Absent','Late','Half Day','Weekly Off','Holiday','On Leave') NOT NULL DEFAULT 'Present',
  `late_minutes` int(11) DEFAULT '0',
  `early_leaving_minutes` int(11) DEFAULT '0',
  `overtime_minutes` int(11) DEFAULT '0',
  `total_worked_minutes` int(11) DEFAULT '0',
  `is_manual_entry` tinyint(1) DEFAULT '0',
  `remarks` text,
  `approved_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `attendances_tenant_id_employee_id_attendance_date` (`tenant_id`,`employee_id`,`attendance_date`),
  KEY `attendances_tenant_id` (`tenant_id`),
  KEY `attendances_employee_id` (`employee_id`),
  KEY `attendances_attendance_date` (`attendance_date`),
  KEY `attendances_status` (`status`),
  KEY `attendances_shift_id` (`shift_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `benefit_types` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(150) NOT NULL,
  `benefit_category` enum('Medical','Insurance','Travel','Education','Housing','Transportation','Other') NOT NULL,
  `provider_name` varchar(200) DEFAULT NULL,
  `coverage_details` text,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `benefit_types_tenant_id_code` (`tenant_id`,`code`),
  KEY `benefit_types_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `branches` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_ar` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` text COLLATE utf8mb4_unicode_ci,
  `city` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_head_office` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_branch_tenant_code` (`tenant_id`,`code`),
  UNIQUE KEY `branches_tenant_id_code` (`tenant_id`,`code`),
  KEY `idx_branch_tenant` (`tenant_id`),
  KEY `branches_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cost_centers` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_ar` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `department_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_cc_tenant_code` (`tenant_id`,`code`),
  UNIQUE KEY `cost_centers_tenant_id_code` (`tenant_id`,`code`),
  KEY `idx_cc_tenant` (`tenant_id`),
  KEY `idx_cc_dept` (`department_id`),
  KEY `cost_centers_tenant_id` (`tenant_id`),
  KEY `cost_centers_department_id` (`department_id`),
  CONSTRAINT `cost_centers_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `deduction_types` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(150) NOT NULL,
  `deduction_category` enum('Loan','Absence','Late','Penalty','Insurance','Other') DEFAULT 'Other',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `deduction_types_tenant_id_code` (`tenant_id`,`code`),
  KEY `deduction_types_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `departments` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_ar` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parent_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `branch_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `manager_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `is_active` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `created_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_dept_tenant_code` (`tenant_id`,`code`),
  UNIQUE KEY `departments_tenant_id_code` (`tenant_id`,`code`),
  KEY `idx_dept_tenant` (`tenant_id`),
  KEY `idx_dept_branch` (`branch_id`),
  KEY `idx_dept_parent` (`parent_id`),
  KEY `departments_tenant_id` (`tenant_id`),
  KEY `departments_branch_id` (`branch_id`),
  KEY `departments_parent_id` (`parent_id`),
  KEY `manager_id` (`manager_id`),
  CONSTRAINT `departments_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `departments_ibfk_2` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `departments_ibfk_3` FOREIGN KEY (`manager_id`) REFERENCES `employees` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `designations` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_ar` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `department_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `grade` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `is_active` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `created_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_desig_tenant_code` (`tenant_id`,`code`),
  UNIQUE KEY `designations_tenant_id_code` (`tenant_id`,`code`),
  KEY `idx_desig_tenant` (`tenant_id`),
  KEY `idx_desig_dept` (`department_id`),
  KEY `designations_tenant_id` (`tenant_id`),
  KEY `designations_department_id` (`department_id`),
  CONSTRAINT `designations_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employee_allowances` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `allowance_type_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL,
  `effective_from` date DEFAULT NULL,
  `effective_to` date DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_allowances_tenant_id` (`tenant_id`),
  KEY `employee_allowances_employee_id` (`employee_id`),
  KEY `employee_allowances_allowance_type_id` (`allowance_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `employee_benefits` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `benefit_type_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `enrolled_date` date DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `coverage_amount` decimal(12,2) DEFAULT '0.00',
  `employer_contribution` decimal(12,2) DEFAULT '0.00',
  `employee_contribution` decimal(12,2) DEFAULT '0.00',
  `status` enum('Active','Inactive','Expired','Cancelled') DEFAULT 'Active',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_benefits_tenant_id` (`tenant_id`),
  KEY `employee_benefits_employee_id` (`employee_id`),
  KEY `employee_benefits_benefit_type_id` (`benefit_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `employee_deductions` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `deduction_type_id` char(36) DEFAULT NULL,
  `loan_id` char(36) DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL,
  `effective_from` date DEFAULT NULL,
  `effective_to` date DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_deductions_tenant_id` (`tenant_id`),
  KEY `employee_deductions_employee_id` (`employee_id`),
  KEY `employee_deductions_deduction_type_id` (`deduction_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `employee_documents` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `employee_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `document_type` enum('Contract','Passport','Visa','EmiratesID','LaborCard','Certificate','OfferLetter','Warning','Other') COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_size` int(11) DEFAULT NULL,
  `mime_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `issue_date` date DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_by` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_doc_tenant` (`tenant_id`),
  KEY `idx_doc_employee` (`employee_id`),
  KEY `idx_doc_type` (`document_type`),
  KEY `idx_doc_expiry` (`expiry_date`),
  KEY `employee_documents_tenant_id` (`tenant_id`),
  KEY `employee_documents_employee_id` (`employee_id`),
  KEY `employee_documents_document_type` (`document_type`),
  KEY `employee_documents_expiry_date` (`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employee_loans` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `loan_number` varchar(30) NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `loan_type` enum('Personal','Housing','Vehicle','Education','Medical','Other') DEFAULT 'Personal',
  `principal_amount` decimal(12,2) NOT NULL,
  `interest_rate` decimal(5,2) DEFAULT '0.00',
  `monthly_installment` decimal(12,2) NOT NULL,
  `total_installments` int(11) NOT NULL,
  `paid_installments` int(11) DEFAULT '0',
  `remaining_amount` decimal(12,2) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `status` enum('Pending','Approved','Active','Closed','Suspended','Rejected') DEFAULT 'Pending',
  `approved_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_loans_tenant_id` (`tenant_id`),
  KEY `employee_loans_employee_id` (`employee_id`),
  KEY `employee_loans_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `employee_salaries` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `structure_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `effective_from` date NOT NULL,
  `effective_to` date DEFAULT NULL,
  `basic_salary` decimal(12,2) NOT NULL,
  `gross_salary` decimal(12,2) DEFAULT '0.00',
  `net_salary` decimal(12,2) DEFAULT '0.00',
  `currency` varchar(3) DEFAULT 'AED',
  `payment_mode` enum('Bank Transfer','Cash','Cheque','WPS') DEFAULT 'Bank Transfer',
  `bank_name` varchar(150) DEFAULT NULL,
  `bank_account_number` varchar(50) DEFAULT NULL,
  `iban` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_salaries_tenant_id` (`tenant_id`),
  KEY `employee_salaries_employee_id` (`employee_id`),
  KEY `employee_salaries_structure_id` (`structure_id`),
  KEY `employee_salaries_effective_from` (`effective_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `employees` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `employee_code` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `first_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `middle_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `full_name_ar` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gender` enum('Male','Female','Other') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `place_of_birth` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nationality` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `religion` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `marital_status` enum('Single','Married','Divorced','Widowed') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `blood_group` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `personal_email` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `work_email` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobile_number` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `work_phone` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emergency_contact_name` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emergency_contact_number` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emergency_contact_relation` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_line1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_line2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postal_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `passport_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `passport_issue_date` date DEFAULT NULL,
  `passport_expiry_date` date DEFAULT NULL,
  `passport_issue_country` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visa_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visa_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visa_issue_date` date DEFAULT NULL,
  `visa_expiry_date` date DEFAULT NULL,
  `visa_issue_place` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emirates_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emirates_id_expiry_date` date DEFAULT NULL,
  `labor_card_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `labor_card_expiry_date` date DEFAULT NULL,
  `joining_date` date DEFAULT NULL,
  `confirmation_date` date DEFAULT NULL,
  `contract_start_date` date DEFAULT NULL,
  `contract_end_date` date DEFAULT NULL,
  `contract_type` enum('Limited','Unlimited','Part-Time','Contractor','Intern','Probation') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employment_type` enum('Full-Time','Part-Time','Contract','Temporary','Intern','Consultant') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `probation_end_date` date DEFAULT NULL,
  `resignation_date` date DEFAULT NULL,
  `last_working_date` date DEFAULT NULL,
  `termination_date` date DEFAULT NULL,
  `termination_reason` text COLLATE utf8mb4_unicode_ci,
  `department_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `designation_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `branch_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cost_center_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reporting_manager_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `basic_salary` decimal(12,2) DEFAULT '0.00',
  `housing_allowance` decimal(12,2) DEFAULT '0.00',
  `transport_allowance` decimal(12,2) DEFAULT '0.00',
  `other_allowances` decimal(12,2) DEFAULT '0.00',
  `total_salary` decimal(12,2) DEFAULT '0.00',
  `salary_currency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT 'AED',
  `bank_name` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_account_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iban` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `swift_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `wps_agent_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('Active','Inactive','On Leave','Suspended','Terminated','Resigned','Retired') COLLATE utf8mb4_unicode_ci DEFAULT 'Active',
  `photo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_emp_tenant_code` (`tenant_id`,`employee_code`),
  UNIQUE KEY `employees_tenant_id_employee_code` (`tenant_id`,`employee_code`),
  KEY `idx_emp_tenant` (`tenant_id`),
  KEY `idx_emp_dept` (`department_id`),
  KEY `idx_emp_desig` (`designation_id`),
  KEY `idx_emp_branch` (`branch_id`),
  KEY `idx_emp_cost_center` (`cost_center_id`),
  KEY `idx_emp_manager` (`reporting_manager_id`),
  KEY `idx_emp_status` (`status`),
  KEY `idx_emp_joining` (`joining_date`),
  KEY `idx_emp_contract_end` (`contract_end_date`),
  KEY `employees_tenant_id` (`tenant_id`),
  KEY `employees_department_id` (`department_id`),
  KEY `employees_designation_id` (`designation_id`),
  KEY `employees_branch_id` (`branch_id`),
  KEY `employees_cost_center_id` (`cost_center_id`),
  KEY `employees_reporting_manager_id` (`reporting_manager_id`),
  KEY `employees_status` (`status`),
  KEY `employees_joining_date` (`joining_date`),
  KEY `employees_contract_end_date` (`contract_end_date`),
  CONSTRAINT `employees_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employees_ibfk_2` FOREIGN KEY (`designation_id`) REFERENCES `designations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employees_ibfk_3` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employees_ibfk_4` FOREIGN KEY (`cost_center_id`) REFERENCES `cost_centers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employees_ibfk_5` FOREIGN KEY (`reporting_manager_id`) REFERENCES `employees` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `eosb_calculations` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `calculation_date` date NOT NULL,
  `joining_date` date NOT NULL,
  `last_working_date` date NOT NULL,
  `years_of_service` decimal(5,2) NOT NULL,
  `basic_salary` decimal(12,2) NOT NULL,
  `termination_type` enum('Resignation','Termination','Retirement','Death','ContractEnd') NOT NULL,
  `daily_wage` decimal(10,2) DEFAULT '0.00',
  `first_5_years_amount` decimal(12,2) DEFAULT '0.00',
  `after_5_years_amount` decimal(12,2) DEFAULT '0.00',
  `total_eosb_amount` decimal(12,2) DEFAULT '0.00',
  `max_cap_amount` decimal(12,2) DEFAULT '0.00' COMMENT '2 years salary cap per UAE law',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `eosb_calculations_tenant_id` (`tenant_id`),
  KEY `eosb_calculations_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `eosb_settlements` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `settlement_number` varchar(30) NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `calculation_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `settlement_date` date NOT NULL,
  `eosb_amount` decimal(12,2) DEFAULT '0.00',
  `leave_encashment` decimal(12,2) DEFAULT '0.00',
  `gratuity_amount` decimal(12,2) DEFAULT '0.00',
  `other_dues` decimal(12,2) DEFAULT '0.00',
  `deductions` decimal(12,2) DEFAULT '0.00',
  `net_settlement` decimal(12,2) DEFAULT '0.00',
  `payment_mode` enum('Bank Transfer','Cash','Cheque') DEFAULT 'Bank Transfer',
  `status` enum('Draft','Calculated','Approved','Paid') DEFAULT 'Draft',
  `approved_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `paid_date` date DEFAULT NULL,
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `eosb_settlements_tenant_id` (`tenant_id`),
  KEY `eosb_settlements_employee_id` (`employee_id`),
  KEY `eosb_settlements_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ess_submissions` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `request_type` enum('Leave','Loan','Document','ProfileUpdate','Payslip','Attendance','Other') NOT NULL,
  `reference_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `title` varchar(200) NOT NULL,
  `description` text,
  `status` enum('Pending','Approved','Rejected','Completed') DEFAULT 'Pending',
  `reviewed_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `remarks` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ess_submissions_tenant_id` (`tenant_id`),
  KEY `ess_submissions_employee_id` (`employee_id`),
  KEY `ess_submissions_request_type` (`request_type`),
  KEY `ess_submissions_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `exit_interviews` (
  `id` char(36) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `employee_id` char(36) NOT NULL,
  `interview_date` date NOT NULL,
  `reason_for_leaving` text,
  `new_employer` varchar(200) DEFAULT NULL,
  `new_position` varchar(200) DEFAULT NULL,
  `feedback` text,
  `rehire_recommendation` tinyint(1) DEFAULT NULL,
  `interviewer_id` char(36) DEFAULT NULL,
  `status` enum('Scheduled','Completed','Cancelled') DEFAULT 'Scheduled',
  `created_by` char(36) DEFAULT NULL,
  `updated_by` char(36) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ei_tenant` (`tenant_id`),
  KEY `idx_ei_employee` (`employee_id`),
  KEY `exit_interviews_tenant_id` (`tenant_id`),
  KEY `exit_interviews_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `holidays` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `name` varchar(150) NOT NULL,
  `name_ar` varchar(150) DEFAULT NULL,
  `holiday_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `is_recurring_yearly` tinyint(1) DEFAULT '0',
  `holiday_type` enum('Public','Religious','National','Company') DEFAULT 'Public',
  `description` text,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `holidays_tenant_id` (`tenant_id`),
  KEY `holidays_holiday_date` (`holiday_date`),
  KEY `holidays_holiday_type` (`holiday_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `interviews` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `applicant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `interview_date` date NOT NULL,
  `interview_time` time DEFAULT NULL,
  `interviewer_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `interview_type` enum('Phone','Video','InPerson','Technical','HR') DEFAULT 'InPerson',
  `round_number` int(11) DEFAULT '1',
  `status` enum('Scheduled','Completed','Cancelled','NoShow') DEFAULT 'Scheduled',
  `rating` int(11) DEFAULT NULL COMMENT '1-5 rating',
  `feedback` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `interviews_tenant_id` (`tenant_id`),
  KEY `interviews_applicant_id` (`applicant_id`),
  KEY `interviews_interview_date` (`interview_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `job_applicants` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `position_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `applicant_number` varchar(30) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `resume_path` varchar(500) DEFAULT NULL,
  `experience_years` int(11) DEFAULT NULL,
  `current_company` varchar(200) DEFAULT NULL,
  `current_salary` decimal(10,2) DEFAULT NULL,
  `expected_salary` decimal(10,2) DEFAULT NULL,
  `source` enum('LinkedIn','Website','Referral','Agency','JobPortal','Other') DEFAULT 'Website',
  `status` enum('Applied','Shortlisted','Interviewed','Offered','Hired','Rejected') DEFAULT 'Applied',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `job_applicants_tenant_id` (`tenant_id`),
  KEY `job_applicants_position_id` (`position_id`),
  KEY `job_applicants_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `job_positions` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `position_code` varchar(30) NOT NULL,
  `title` varchar(200) NOT NULL,
  `department_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `designation_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `vacancies` int(11) DEFAULT '1',
  `min_experience` int(11) DEFAULT '0',
  `max_experience` int(11) DEFAULT NULL,
  `min_salary` decimal(10,2) DEFAULT NULL,
  `max_salary` decimal(10,2) DEFAULT NULL,
  `posting_date` date DEFAULT NULL,
  `closing_date` date DEFAULT NULL,
  `status` enum('Draft','Open','Closed','Filled','Cancelled') DEFAULT 'Draft',
  `description` text,
  `requirements` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `job_positions_tenant_id` (`tenant_id`),
  KEY `job_positions_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `leave_applications` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `application_number` varchar(30) NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `leave_type_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `total_days` decimal(5,1) DEFAULT '0.0',
  `reason` text,
  `status` enum('Draft','Submitted','Approved','Rejected','Cancelled') DEFAULT 'Draft',
  `contact_details` varchar(200) DEFAULT NULL,
  `attachment_path` varchar(500) DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `leave_applications_tenant_id` (`tenant_id`),
  KEY `leave_applications_employee_id` (`employee_id`),
  KEY `leave_applications_leave_type_id` (`leave_type_id`),
  KEY `leave_applications_status` (`status`),
  KEY `leave_applications_start_date_end_date` (`start_date`,`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `leave_approvals` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `leave_application_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `approver_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `approval_level` int(11) DEFAULT '1',
  `status` enum('Pending','Approved','Rejected') DEFAULT 'Pending',
  `comments` text,
  `decided_at` datetime DEFAULT NULL,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `leave_approvals_tenant_id` (`tenant_id`),
  KEY `leave_approvals_leave_application_id` (`leave_application_id`),
  KEY `leave_approvals_approver_id` (`approver_id`),
  KEY `leave_approvals_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `leave_balances` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `leave_type_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `year` int(11) NOT NULL,
  `opening_balance` decimal(5,1) DEFAULT '0.0',
  `accrued_days` decimal(5,1) DEFAULT '0.0',
  `used_days` decimal(5,1) DEFAULT '0.0',
  `pending_days` decimal(5,1) DEFAULT '0.0',
  `available_balance` decimal(5,1) DEFAULT '0.0',
  `carry_forward_days` decimal(5,1) DEFAULT '0.0',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `leave_balances_tenant_id_employee_id_leave_type_id_year` (`tenant_id`,`employee_id`,`leave_type_id`,`year`),
  KEY `leave_balances_tenant_id` (`tenant_id`),
  KEY `leave_balances_employee_id` (`employee_id`),
  KEY `leave_balances_leave_type_id` (`leave_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `leave_types` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(100) NOT NULL,
  `name_ar` varchar(100) DEFAULT NULL,
  `leave_category` enum('Annual','Sick','Emergency','Maternity','Paternity','Unpaid','Compensatory','Bereavement','Study','Other') NOT NULL,
  `is_paid` tinyint(1) DEFAULT '1',
  `max_days_per_year` decimal(5,1) DEFAULT NULL,
  `max_days_per_request` decimal(5,1) DEFAULT NULL,
  `min_days_per_request` decimal(4,1) DEFAULT '0.5',
  `requires_approval` tinyint(1) DEFAULT '1',
  `requires_documents` tinyint(1) DEFAULT '0',
  `allow_negative_balance` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `description` text,
  `color` varchar(7) DEFAULT NULL,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `leave_types_tenant_id_code` (`tenant_id`,`code`),
  KEY `leave_types_tenant_id` (`tenant_id`),
  KEY `leave_types_leave_category` (`leave_category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `loan_repayments` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `loan_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `installment_number` int(11) NOT NULL,
  `due_date` date NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `principal_portion` decimal(12,2) DEFAULT '0.00',
  `interest_portion` decimal(12,2) DEFAULT '0.00',
  `paid_date` date DEFAULT NULL,
  `status` enum('Pending','Paid','Skipped') DEFAULT 'Pending',
  `payroll_run_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loan_repayments_tenant_id` (`tenant_id`),
  KEY `loan_repayments_loan_id` (`loan_id`),
  KEY `loan_repayments_employee_id` (`employee_id`),
  KEY `loan_repayments_payroll_run_id` (`payroll_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `master_cities` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `state_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `country_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `name` varchar(150) NOT NULL,
  `name_ar` varchar(150) DEFAULT NULL,
  `is_system` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `country_id` (`country_id`),
  KEY `master_cities_tenant_id_country_id` (`tenant_id`,`country_id`),
  KEY `master_cities_state_id_name` (`state_id`,`name`),
  CONSTRAINT `master_cities_ibfk_1` FOREIGN KEY (`state_id`) REFERENCES `master_states` (`id`),
  CONSTRAINT `master_cities_ibfk_2` FOREIGN KEY (`country_id`) REFERENCES `master_countries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `master_countries` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(5) NOT NULL COMMENT 'ISO 3166-1 alpha-2',
  `name` varchar(150) NOT NULL,
  `name_ar` varchar(150) DEFAULT NULL,
  `nationality` varchar(100) DEFAULT NULL,
  `nationality_ar` varchar(100) DEFAULT NULL,
  `phone_code` varchar(10) DEFAULT NULL,
  `currency_code` varchar(5) DEFAULT NULL,
  `currency_symbol` varchar(5) DEFAULT NULL,
  `flag_emoji` varchar(10) DEFAULT NULL,
  `is_system` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `master_countries_tenant_id_code` (`tenant_id`,`code`),
  KEY `master_countries_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `master_data` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `type` varchar(50) NOT NULL COMMENT 'Entity type: employment_type, leave_type, skill, etc.',
  `code` varchar(50) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `name_ar` varchar(200) DEFAULT NULL,
  `description` text,
  `parent_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `metadata` json DEFAULT NULL COMMENT 'Extra type-specific fields',
  `is_system` tinyint(1) DEFAULT '0',
  `is_default` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `deleted_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `master_data_tenant_id_type_code` (`tenant_id`,`type`,`code`),
  KEY `master_data_tenant_id_type_is_active` (`tenant_id`,`type`,`is_active`),
  KEY `master_data_type_name` (`type`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `master_data_audit` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `record_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `record_type` varchar(50) NOT NULL,
  `user_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `action` enum('create','update','delete','restore','activate','deactivate') NOT NULL,
  `field_name` varchar(100) DEFAULT NULL,
  `old_value` text,
  `new_value` text,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `master_data_audit_tenant_id_record_type` (`tenant_id`,`record_type`),
  KEY `master_data_audit_record_id` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `master_states` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `country_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(10) DEFAULT NULL,
  `name` varchar(150) NOT NULL,
  `name_ar` varchar(150) DEFAULT NULL,
  `is_system` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `master_states_tenant_id_country_id` (`tenant_id`,`country_id`),
  KEY `master_states_country_id_name` (`country_id`,`name`),
  CONSTRAINT `master_states_ibfk_1` FOREIGN KEY (`country_id`) REFERENCES `master_countries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `offboarding_checklists` (
  `id` char(36) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `task_name` varchar(200) NOT NULL,
  `category` enum('ExitInterview','AssetReturn','ITAccess','FinalSettlement','Documentation','Clearance','Other') DEFAULT 'Other',
  `sort_order` int(11) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ofc_tenant` (`tenant_id`),
  KEY `offboarding_checklists_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `offboarding_progress` (
  `id` char(36) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `employee_id` char(36) NOT NULL,
  `checklist_id` char(36) NOT NULL,
  `completed_date` date DEFAULT NULL,
  `completed_by` char(36) DEFAULT NULL,
  `status` enum('Pending','In Progress','Completed','Skipped') DEFAULT 'Pending',
  `notes` text,
  `created_by` char(36) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ofp_tenant` (`tenant_id`),
  KEY `idx_ofp_employee` (`employee_id`),
  KEY `offboarding_progress_tenant_id` (`tenant_id`),
  KEY `offboarding_progress_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `offer_letters` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `offer_number` varchar(30) NOT NULL,
  `applicant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `position_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `offer_date` date NOT NULL,
  `joining_date` date DEFAULT NULL,
  `offered_salary` decimal(12,2) NOT NULL,
  `status` enum('Draft','Sent','Accepted','Declined','Expired') DEFAULT 'Draft',
  `expiry_date` date DEFAULT NULL,
  `terms_and_conditions` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `offer_letters_tenant_id` (`tenant_id`),
  KEY `offer_letters_applicant_id` (`applicant_id`),
  KEY `offer_letters_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `onboarding_checklists` (
  `id` char(36) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `task_name` varchar(200) NOT NULL,
  `category` enum('IT','HR','Admin','Training','Documentation','Other') DEFAULT 'HR',
  `sort_order` int(11) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_onc_tenant` (`tenant_id`),
  KEY `onboarding_checklists_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `onboarding_progress` (
  `id` char(36) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `employee_id` char(36) NOT NULL,
  `checklist_id` char(36) NOT NULL,
  `completed_date` date DEFAULT NULL,
  `completed_by` char(36) DEFAULT NULL,
  `status` enum('Pending','In Progress','Completed','Skipped') DEFAULT 'Pending',
  `notes` text,
  `created_by` char(36) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_onp_tenant` (`tenant_id`),
  KEY `idx_onp_employee` (`employee_id`),
  KEY `onboarding_progress_tenant_id` (`tenant_id`),
  KEY `onboarding_progress_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `overtime_entries` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `attendance_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `overtime_date` date NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `total_minutes` int(11) DEFAULT '0',
  `overtime_type` enum('Regular','Weekend','Holiday') DEFAULT 'Regular',
  `rate_multiplier` decimal(3,2) DEFAULT '1.25',
  `status` enum('Pending','Approved','Rejected') DEFAULT 'Pending',
  `approved_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `reason` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `overtime_entries_tenant_id` (`tenant_id`),
  KEY `overtime_entries_employee_id` (`employee_id`),
  KEY `overtime_entries_overtime_date` (`overtime_date`),
  KEY `overtime_entries_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `payroll_details` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `payroll_run_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `basic_salary` decimal(12,2) DEFAULT '0.00',
  `allowances` decimal(12,2) DEFAULT '0.00',
  `deductions` decimal(12,2) DEFAULT '0.00',
  `overtime_pay` decimal(12,2) DEFAULT '0.00',
  `loan_deduction` decimal(12,2) DEFAULT '0.00',
  `gross_pay` decimal(12,2) DEFAULT '0.00',
  `net_pay` decimal(12,2) DEFAULT '0.00',
  `employer_contributions` decimal(12,2) DEFAULT '0.00',
  `working_days` int(11) DEFAULT '0',
  `paid_days` int(11) DEFAULT '0',
  `absent_days` int(11) DEFAULT '0',
  `late_minutes` int(11) DEFAULT '0',
  `overtime_hours` decimal(5,2) DEFAULT '0.00',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `payroll_details_tenant_id` (`tenant_id`),
  KEY `payroll_details_payroll_run_id` (`payroll_run_id`),
  KEY `payroll_details_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `payroll_periods` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `period_code` varchar(30) NOT NULL,
  `period_name` varchar(150) NOT NULL,
  `frequency` enum('Monthly','Weekly','BiWeekly','Daily') NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `payment_date` date DEFAULT NULL,
  `status` enum('Open','Processing','Closed','Locked') DEFAULT 'Open',
  `is_locked` tinyint(1) DEFAULT '0',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `payroll_periods_tenant_id_period_code` (`tenant_id`,`period_code`),
  KEY `payroll_periods_tenant_id` (`tenant_id`),
  KEY `payroll_periods_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `payroll_runs` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `run_number` varchar(30) NOT NULL,
  `period_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `run_date` date NOT NULL,
  `total_employees` int(11) DEFAULT '0',
  `total_gross` decimal(14,2) DEFAULT '0.00',
  `total_deductions` decimal(14,2) DEFAULT '0.00',
  `total_net_pay` decimal(14,2) DEFAULT '0.00',
  `total_employer_contributions` decimal(14,2) DEFAULT '0.00',
  `status` enum('Draft','Processed','Approved','Reversed') DEFAULT 'Draft',
  `processed_at` datetime DEFAULT NULL,
  `approved_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `reversed_at` datetime DEFAULT NULL,
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `payroll_runs_tenant_id` (`tenant_id`),
  KEY `payroll_runs_period_id` (`period_id`),
  KEY `payroll_runs_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `payslips` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `payslip_number` varchar(30) NOT NULL,
  `payroll_run_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `basic_salary` decimal(12,2) DEFAULT '0.00',
  `allowance_breakdown` json DEFAULT NULL,
  `deduction_breakdown` json DEFAULT NULL,
  `gross_pay` decimal(12,2) DEFAULT '0.00',
  `net_pay` decimal(12,2) DEFAULT '0.00',
  `payment_date` date DEFAULT NULL,
  `status` enum('Draft','Generated','Sent','Acknowledged') DEFAULT 'Generated',
  `generated_at` datetime DEFAULT NULL,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `payslips_tenant_id` (`tenant_id`),
  KEY `payslips_payroll_run_id` (`payroll_run_id`),
  KEY `payslips_employee_id` (`employee_id`),
  KEY `payslips_payslip_number` (`payslip_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `performance_appraisals` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `appraiser_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `appraisal_date` date NOT NULL,
  `period_from` date DEFAULT NULL,
  `period_to` date DEFAULT NULL,
  `overall_rating` decimal(3,1) DEFAULT NULL,
  `strengths` text,
  `improvements` text,
  `employee_comments` text,
  `appraiser_comments` text,
  `status` enum('Draft','Self Review','Manager Review','Reviewed','Acknowledged') DEFAULT 'Draft',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `performance_appraisals_tenant_id` (`tenant_id`),
  KEY `performance_appraisals_employee_id` (`employee_id`),
  KEY `performance_appraisals_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `performance_goals` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `title` varchar(200) NOT NULL,
  `description` text,
  `goal_type` enum('Individual','Team','Department','Company') DEFAULT 'Individual',
  `priority` enum('Low','Medium','High','Critical') DEFAULT 'Medium',
  `start_date` date DEFAULT NULL,
  `target_date` date DEFAULT NULL,
  `completion_date` date DEFAULT NULL,
  `progress_percentage` int(11) DEFAULT '0',
  `weight` decimal(5,2) DEFAULT '100.00' COMMENT 'Weight in appraisal',
  `status` enum('Not Started','In Progress','Completed','On Hold','Cancelled') DEFAULT 'Not Started',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `performance_goals_tenant_id` (`tenant_id`),
  KEY `performance_goals_employee_id` (`employee_id`),
  KEY `performance_goals_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `performance_kpis` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text,
  `kpi_type` enum('Quantitative','Qualitative','Behavioral') DEFAULT 'Quantitative',
  `measurement_unit` varchar(50) DEFAULT NULL,
  `target_value` decimal(10,2) DEFAULT NULL,
  `minimum_value` decimal(10,2) DEFAULT NULL,
  `department_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `performance_kpis_tenant_id_code` (`tenant_id`,`code`),
  KEY `performance_kpis_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `permissions` (
  `id` char(36) NOT NULL,
  `code` varchar(100) NOT NULL,
  `name` varchar(200) NOT NULL,
  `group` varchar(100) DEFAULT NULL,
  `module` varchar(100) DEFAULT NULL,
  `action` varchar(50) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `idx_code` (`code`),
  KEY `idx_group` (`group`),
  KEY `idx_module` (`module`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `role_permissions` (
  `id` char(36) NOT NULL,
  `role_id` char(36) NOT NULL,
  `permission_id` char(36) NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_perm` (`role_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `roles` (
  `id` char(36) NOT NULL,
  `name` varchar(100) NOT NULL,
  `code` varchar(50) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `is_system` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `created_by` char(36) DEFAULT NULL,
  `updated_by` char(36) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `idx_code` (`code`),
  KEY `idx_system` (`is_system`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rosters` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `shift_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `roster_date` date NOT NULL,
  `is_weekly_off` tinyint(1) DEFAULT '0',
  `is_holiday` tinyint(1) DEFAULT '0',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rosters_tenant_id_employee_id_roster_date` (`tenant_id`,`employee_id`,`roster_date`),
  KEY `rosters_tenant_id` (`tenant_id`),
  KEY `rosters_employee_id` (`employee_id`),
  KEY `rosters_shift_id` (`shift_id`),
  KEY `rosters_roster_date` (`roster_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `salary_components` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `structure_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(150) NOT NULL,
  `component_type` enum('Earning','Deduction','EmployerContribution','EmployeeContribution') NOT NULL,
  `calculation_method` enum('Fixed','Percentage','Formula') DEFAULT 'Fixed',
  `value` decimal(12,2) DEFAULT '0.00',
  `percentage_of` varchar(50) DEFAULT NULL COMMENT 'Which base to calculate percentage on (e.g., basic_salary, total_salary)',
  `is_taxable` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `salary_components_tenant_id` (`tenant_id`),
  KEY `salary_components_structure_id` (`structure_id`),
  KEY `salary_components_component_type` (`component_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `salary_structures` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(150) NOT NULL,
  `description` text,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `salary_structures_tenant_id_code` (`tenant_id`,`code`),
  KEY `salary_structures_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_attendance` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `overtime_enabled` tinyint(1) DEFAULT '1',
  `overtime_daily_limit` int(11) DEFAULT '120',
  `overtime_weekly_limit` int(11) DEFAULT '480',
  `overtime_rate` decimal(4,2) DEFAULT '1.50',
  `overtime_holiday_rate` decimal(4,2) DEFAULT '2.00',
  `auto_deduction_enabled` tinyint(1) DEFAULT '0',
  `late_deduction_type` enum('per_minute','per_hour','fixed') DEFAULT NULL,
  `late_deduction_amount` decimal(10,2) DEFAULT '0.00',
  `biometric_required` tinyint(1) DEFAULT '0',
  `geo_fencing_enabled` tinyint(1) DEFAULT '0',
  `geo_fencing_radius` int(11) DEFAULT '100',
  `ip_restriction_enabled` tinyint(1) DEFAULT '0',
  `allowed_ips` text,
  `half_day_threshold` int(11) DEFAULT '240',
  `absent_threshold` int(11) DEFAULT '480',
  `weekend_overtime_rate` decimal(4,2) DEFAULT '1.50',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_audit_logs` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `user_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `module` varchar(100) NOT NULL,
  `section` varchar(100) NOT NULL,
  `field_name` varchar(100) DEFAULT NULL,
  `old_value` text,
  `new_value` text,
  `action` enum('create','update','delete') NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `settings_audit_logs_tenant_id_module` (`tenant_id`,`module`),
  KEY `settings_audit_logs_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_company_profile` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `profile_type` enum('branch','business_unit','location','cost_center') NOT NULL,
  `name` varchar(200) NOT NULL,
  `code` varchar(50) DEFAULT NULL,
  `parent_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `address` text,
  `phone` varchar(30) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `manager_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `sort_order` int(11) DEFAULT '0',
  `metadata` json DEFAULT NULL,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `settings_company_profile_tenant_id_profile_type` (`tenant_id`,`profile_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_email` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `smtp_host` varchar(255) DEFAULT NULL,
  `smtp_port` int(11) DEFAULT '587',
  `smtp_username` varchar(255) DEFAULT NULL,
  `smtp_password` varchar(500) DEFAULT NULL,
  `smtp_encryption` enum('none','ssl','tls') DEFAULT 'tls',
  `from_name` varchar(150) DEFAULT NULL,
  `from_email` varchar(150) DEFAULT NULL,
  `reply_to` varchar(150) DEFAULT NULL,
  `email_footer` text,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_general` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  `logo_url` varchar(500) DEFAULT NULL,
  `address_line1` varchar(255) DEFAULT NULL,
  `address_line2` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `postal_code` varchar(20) DEFAULT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `tax_number` varchar(50) DEFAULT NULL,
  `default_currency` varchar(5) DEFAULT 'AED',
  `timezone` varchar(50) DEFAULT 'Asia/Dubai',
  `language` varchar(10) DEFAULT 'en',
  `date_format` varchar(20) DEFAULT 'DD/MM/YYYY',
  `time_format` varchar(10) DEFAULT '12h',
  `financial_year_start` varchar(5) DEFAULT '01-01',
  `payroll_start_month` int(11) DEFAULT '1',
  `company_working_days` varchar(50) DEFAULT 'Mon,Tue,Wed,Thu,Fri',
  `week_start_day` varchar(10) DEFAULT 'Monday',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `settings_general_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_leave` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `leave_year_start` varchar(5) DEFAULT '01-01',
  `accrual_method` enum('monthly','quarterly','annual','custom') DEFAULT NULL,
  `accrual_rate` decimal(5,2) DEFAULT '2.50',
  `carry_forward_enabled` tinyint(1) DEFAULT '1',
  `carry_forward_max` int(11) DEFAULT '30',
  `carry_forward_expiry` varchar(5) DEFAULT '03-31',
  `negative_balance_allowed` tinyint(1) DEFAULT '0',
  `negative_balance_max` int(11) DEFAULT '0',
  `approval_workflow` enum('direct_manager','multi_level','hr_only') DEFAULT NULL,
  `auto_approve_enabled` tinyint(1) DEFAULT '0',
  `min_notice_days` int(11) DEFAULT '0',
  `max_consecutive_days` int(11) DEFAULT '0',
  `weekend_included` tinyint(1) DEFAULT '0',
  `holiday_included` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_localization` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `language` varchar(10) DEFAULT 'en',
  `languages_supported` json DEFAULT NULL COMMENT '["en","ar"]',
  `currency` varchar(5) DEFAULT 'AED',
  `currency_symbol` varchar(5) DEFAULT 'Ø¯.Ø¥',
  `date_format` varchar(20) DEFAULT 'DD/MM/YYYY',
  `number_format` varchar(20) DEFAULT '#,###.##',
  `timezone` varchar(50) DEFAULT 'Asia/Dubai',
  `country` varchar(2) DEFAULT 'AE' COMMENT 'ISO 3166-1 alpha-2',
  `regional_holidays_enabled` tinyint(1) DEFAULT '1',
  `country_specific_rules` json DEFAULT NULL,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `settings_localization_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_notifications` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `email_notifications` tinyint(1) DEFAULT '1',
  `sms_notifications` tinyint(1) DEFAULT '0',
  `push_notifications` tinyint(1) DEFAULT '1',
  `leave_alert` tinyint(1) DEFAULT '1',
  `attendance_alert` tinyint(1) DEFAULT '1',
  `payroll_alert` tinyint(1) DEFAULT '1',
  `document_expiry_alert` tinyint(1) DEFAULT '1',
  `birthday_alert` tinyint(1) DEFAULT '1',
  `onboarding_alert` tinyint(1) DEFAULT '1',
  `alert_days_before` int(11) DEFAULT '7',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_payroll` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `payroll_frequency` enum('monthly','bi-weekly','weekly') DEFAULT NULL,
  `pay_day` int(11) DEFAULT '28',
  `salary_cutoff_day` int(11) DEFAULT '25',
  `wps_enabled` tinyint(1) DEFAULT '1',
  `wps_agent_code` varchar(50) DEFAULT NULL,
  `basic_salary_percentage` decimal(5,2) DEFAULT '60.00',
  `housing_allowance_percentage` decimal(5,2) DEFAULT '20.00',
  `transport_allowance_percentage` decimal(5,2) DEFAULT '10.00',
  `other_allowance_percentage` decimal(5,2) DEFAULT '10.00',
  `overtime_calculation` enum('basic_only','gross_salary') DEFAULT NULL,
  `deduction_calculation` enum('gross','basic') DEFAULT NULL,
  `tax_enabled` tinyint(1) DEFAULT '0',
  `social_security_enabled` tinyint(1) DEFAULT '0',
  `social_security_rate` decimal(5,2) DEFAULT '0.00',
  `gratuity_enabled` tinyint(1) DEFAULT '1',
  `gratuity_calculation` enum('basic_salary','gross_salary') DEFAULT NULL,
  `payslip_language` varchar(10) DEFAULT 'en',
  `payslip_format` varchar(20) DEFAULT 'pdf',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_security` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `password_min_length` int(11) DEFAULT '8',
  `password_complexity` enum('low','medium','high') DEFAULT NULL,
  `password_expiry_days` int(11) DEFAULT '90',
  `session_timeout_minutes` int(11) DEFAULT '30',
  `max_login_attempts` int(11) DEFAULT '5',
  `lockout_duration_minutes` int(11) DEFAULT '15',
  `mfa_enabled` tinyint(1) DEFAULT '0',
  `mfa_type` enum('sms','email','authenticator') DEFAULT NULL,
  `ip_whitelisting_enabled` tinyint(1) DEFAULT '0',
  `allowed_ips` text,
  `audit_log_retention_days` int(11) DEFAULT '90',
  `data_encryption_enabled` tinyint(1) DEFAULT '1',
  `force_password_reset` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_sms` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `provider` enum('twilio','nexmo','infobip','custom') DEFAULT NULL,
  `api_key` varchar(500) DEFAULT NULL,
  `api_secret` varchar(500) DEFAULT NULL,
  `sender_id` varchar(20) DEFAULT NULL,
  `api_url` varchar(500) DEFAULT NULL,
  `daily_limit` int(11) DEFAULT '1000',
  `balance_alert_threshold` int(11) DEFAULT '100',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings_working_hours` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `working_days` varchar(50) DEFAULT 'Mon,Tue,Wed,Thu,Fri',
  `weekend_days` varchar(30) DEFAULT 'Sat,Sun',
  `work_start_time` time DEFAULT '09:00:00',
  `work_end_time` time DEFAULT '18:00:00',
  `break_start_time` time DEFAULT NULL,
  `break_duration_minutes` int(11) DEFAULT '0',
  `lunch_start_time` time DEFAULT NULL,
  `lunch_duration_minutes` int(11) DEFAULT '60',
  `grace_period_minutes` int(11) DEFAULT '15',
  `late_arrival_policy` enum('deduct_leave','deduct_salary','warning','flexible') DEFAULT 'warning',
  `late_deduction_type` enum('per_minute','per_hour','half_day','full_day') DEFAULT NULL,
  `early_departure_policy` enum('deduct_leave','deduct_salary','warning','flexible') DEFAULT 'warning',
  `flexible_hours_enabled` tinyint(1) DEFAULT '0',
  `flexible_start_time` time DEFAULT NULL,
  `flexible_end_time` time DEFAULT NULL,
  `night_shift_start` time DEFAULT NULL,
  `night_shift_end` time DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `settings_working_hours_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `shift_assignments` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `shift_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `assigned_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `effective_from` date NOT NULL,
  `effective_to` date DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `shift_assignments_tenant_id` (`tenant_id`),
  KEY `shift_assignments_employee_id` (`employee_id`),
  KEY `shift_assignments_shift_id` (`shift_id`),
  KEY `shift_assignments_effective_from_effective_to` (`effective_from`,`effective_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `shifts` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(100) NOT NULL,
  `shift_type` enum('Morning','Evening','Night','Rotational','Flexible') NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `grace_period_minutes` int(11) DEFAULT '15',
  `late_threshold_minutes` int(11) DEFAULT '30',
  `half_day_threshold_minutes` int(11) DEFAULT '240',
  `early_leaving_threshold_minutes` int(11) DEFAULT '15',
  `break_start_time` time DEFAULT NULL,
  `break_end_time` time DEFAULT NULL,
  `total_working_hours` decimal(4,2) DEFAULT NULL,
  `weekly_off_days` varchar(50) DEFAULT NULL COMMENT 'Comma-separated day numbers: 0=Sun,1=Mon,...,6=Sat',
  `is_night_shift` tinyint(1) DEFAULT '0',
  `color` varchar(7) DEFAULT NULL COMMENT 'Hex color for UI display',
  `description` text,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `shifts_tenant_id_code` (`tenant_id`,`code`),
  KEY `shifts_tenant_id` (`tenant_id`),
  KEY `shifts_shift_type` (`shift_type`),
  KEY `shifts_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `training_attendees` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `session_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `employee_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `attendance_status` enum('Enrolled','Attended','Absent','Completed') DEFAULT 'Enrolled',
  `score` decimal(5,2) DEFAULT NULL,
  `certificate_issued` tinyint(1) DEFAULT '0',
  `feedback` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `training_attendees_tenant_id` (`tenant_id`),
  KEY `training_attendees_session_id` (`session_id`),
  KEY `training_attendees_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `training_courses` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text,
  `category` enum('Technical','Soft Skills','Compliance','Leadership','Safety','Other') DEFAULT 'Other',
  `duration_hours` int(11) DEFAULT NULL,
  `cost` decimal(10,2) DEFAULT '0.00',
  `provider_name` varchar(200) DEFAULT NULL,
  `is_internal` tinyint(1) DEFAULT '1',
  `is_mandatory` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `training_courses_tenant_id_code` (`tenant_id`,`code`),
  KEY `training_courses_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `training_sessions` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `course_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `session_name` varchar(200) NOT NULL,
  `trainer_name` varchar(200) DEFAULT NULL,
  `location` varchar(200) DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `max_attendees` int(11) DEFAULT NULL,
  `enrolled_count` int(11) DEFAULT '0',
  `status` enum('Planned','In Progress','Completed','Cancelled') DEFAULT 'Planned',
  `notes` text,
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `training_sessions_tenant_id` (`tenant_id`),
  KEY `training_sessions_course_id` (`course_id`),
  KEY `training_sessions_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_companies` (
  `id` char(36) NOT NULL,
  `user_id` char(36) NOT NULL,
  `company_id` char(36) NOT NULL,
  `is_default` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_company` (`user_id`,`company_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_company` (`company_id`),
  CONSTRAINT `user_companies_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `user_roles` (
  `id` char(36) NOT NULL,
  `user_id` char(36) NOT NULL,
  `role_id` char(36) NOT NULL,
  `is_default` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_role` (`user_id`,`role_id`),
  KEY `role_id` (`role_id`),
  CONSTRAINT `user_roles_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_roles_ibfk_2` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `users` (
  `id` char(36) NOT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `password` varchar(255) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `profile_picture` varchar(500) DEFAULT NULL,
  `role` enum('super_admin','company_admin','hr_manager','payroll_manager','hr_officer','recruitment_officer','attendance_officer','department_manager','branch_manager','finance_manager','employee','read_only','auditor','custom') DEFAULT 'employee',
  `is_active` tinyint(1) DEFAULT '1',
  `is_locked` tinyint(1) DEFAULT '0',
  `locked_at` datetime DEFAULT NULL,
  `login_attempts` int(11) DEFAULT '0',
  `last_login_at` datetime DEFAULT NULL,
  `last_login_ip` varchar(45) DEFAULT NULL,
  `password_changed_at` datetime DEFAULT NULL,
  `must_change_password` tinyint(1) DEFAULT '0',
  `mfa_enabled` tinyint(1) DEFAULT '0',
  `mfa_secret` varchar(255) DEFAULT NULL,
  `created_by` char(36) DEFAULT NULL,
  `updated_by` char(36) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_role` (`role`),
  KEY `idx_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `wps_configurations` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `config_name` varchar(100) NOT NULL,
  `bank_code` varchar(50) DEFAULT NULL,
  `agent_code` varchar(50) DEFAULT NULL,
  `file_format` enum('SIF','CSV','EXCEL') DEFAULT 'SIF',
  `employer_reference` varchar(100) DEFAULT NULL,
  `is_default` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `updated_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `wps_configurations_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `wps_exports` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `tenant_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `export_number` varchar(30) NOT NULL,
  `config_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `payroll_run_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `export_date` date NOT NULL,
  `total_employees` int(11) DEFAULT '0',
  `total_amount` decimal(14,2) DEFAULT '0.00',
  `file_name` varchar(255) DEFAULT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `status` enum('Draft','Generated','Submitted') DEFAULT 'Draft',
  `created_by` char(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `wps_exports_tenant_id` (`tenant_id`),
  KEY `wps_exports_payroll_run_id` (`payroll_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
